# the name of your track or event
name = "Q Blockchain Meetup & Cowork"

# the name of the group organizing the event
org = "Q"

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@gerritma"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = "https://www.eventbrite.de/e/q-blockchain-meetup-cowork-tickets-443336781247"

# the start date of the event
date = "2022-11-01"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "11:00 - 19:00"

# the event venue name (will show up on the event card - TODO)
venueName = "[MEX Factory] (https://g.page/mexfactory?share)"

# the event venue address (will show up on a map -- TODO)
venueAddress = "Rua Rodrigues Faria, 103 Edifício H, Piso 0, Espaço 0.09A, 1300-501 Lisboa, Portuga"

# the max number of attendees of the event
attendees = "100"

# these is unsued:
tickets = "NFT"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Cowork", "Meetup","Food","Networking"]

# a color, to group key events visually. use sparingly
color="blue"

# A small logomark for the corner of the event (logomark image can be placed in "/website/public/logomarks")
# logomark = "/logomarks/q.png"

# a description of the track.
# will show up when the user clicks the event card.
description = """

If you are in Lisbon for Filecoin Lisbon, the Websummit and other conferences and looking for a place where you can take a break with your laptop to catch up on work, come and join our Q team’s coworking meetup at Lisbon’s MEX Factory on November 1st. 

Our Q co-working space will be open from 11 am to 7 pm. Enjoy free food and drinks, and recharge your devices at one of our workstations*.

* seats are limited and must be pre-booked by minting an NFT ticket. 

Don’t forget to come and say hi to the Q team, who will be in MEX Factory throughout the day, eager to speak about blockchain governance and why Web3 needs to excel beyond “code is law”.

Engage with the Q Blockchain, earn Q tokens, talk to the Q team about: 

- The Q-native governance frameworks.
- What constitutes good governance in Web3.
- How projects and dApps can benefit from implementing decentralized governance that goes beyond “code is law”.

To access the event and its free food and drinks, mint your NFT ticket. Minting will be enabled a few days before the event

Doors open at 11 am. First Come, first served.

Date: Tuesday, 01.11.2022

Timing: 11 am-7 pm

Place: MEX Factory, Rua Rodrigues Faria, 103, 1300-501 Lisboa, Portugal 

About Q: 

Q is the decentralized governance system for the Web3. 

Its novel Layer-1 public blockchain offers a governance protocol meticulously designed for Web3 entities. Instead of building a governance system from scratch, any company, community, or DAO can integrate with Q. Its human-centred, ready-to-use, fully decentralised governance infrastructure makes it easy to launch bespoke, secure and fair processes for decision-making, enforcement and dispute resolution. Q’s modern governance approach bridges “code is law” with humanity's most established and equitable legal systems, making it possible for automated efficiency and human complexity to co-exist online. Q is an open-source project supported by the Q International Foundation.
 

To learn more, visit https://q.org  

Join the Discord: https://discord.com/invite/YTgkvJvZGD 

Follow Q on Twitter: https://twitter.com/QBlockchain  


"""


# the priority in the schedule table, leave commented if you don't need to control this
# 1 will appear at the top, higher numbers appear closer to bottom
priority = 2

